/*

    # Complexity Management
     - Complexity Management means handling the increased complexity that arises when one application is split into many independent microservices.

     In a Monolithic application:
        One Application
        Everything is in one place.

     In Microservices:
        Login Service
        Product Service
        Order Service
        Payment Service
        Inventory Service
        Notification Service
        Review Service
        Instead of managing 1 application, you now manage many applications.

        This increases system complexity.

    Real-Life Analogy
     Shopping Mall
        Managing one small shop is easy.
        Managing an entire shopping mall with:
            200 shops
            Security
            Electricity
            Parking
            Cleaning
            Maintenance
        is much more complex.

        Microservices are similar.

    Advantages (of Managing Complexity Well)
        Better organization
        Independent teams
        Easier maintenance
        Faster development

    # Inter-Service Communication
     - Microservices communicate with each other using network calls instead of direct method calls.

     Why do we need it?
        Suppose Order Service needs payment confirmation.
        Order Service cannot directly call a Java method inside Payment Service because they are separate applications.
        Instead, they communicate over the network.

    Real-Life Analogy
     Phone Call
        Suppose you need information from another department.
        You don't walk into their computer.
        You:
            Call them
            Send an email
            Send a message
        Microservices communicate similarly.

    Challenges
        Network delay
        Timeout
        Service unavailable
        Retry failures
        Security
        Serialization issues

    # Data Consistency
     - Maintaining correct and synchronized data across multiple microservices is called Data Consistency.

     Why do we need it?
     Remember:
        Each service has its own database.

     Example:
        Order Service
            ↓
        Order Database

        Payment Service
            ↓
        Payment Database

        Suppose: Order created successfully.
                 Payment failed.

        Now what?

        Order Database says: Order Created
        Payment Database says: Payment Failed

        The system becomes inconsistent.

    Real-Life Analogy
     Bank Transfer
        Suppose ₹1000 leaves Account A.

        But
        Bank server crashes before adding ₹1000 to Account B.
        Money disappears.
        Banks solve this carefully.

        Microservices face similar challenges.

     Solutions
        We'll study later:
            Saga Pattern
            Event Sourcing
            CQRS
        These patterns help maintain consistency.

    # Monitoring & Logging
        Monitoring means tracking the health and performance of services.
        Logging means recording events and errors generated by services.

     Why do we need it?
      Suppose there are:
        50 Microservices

        One service fails.

        How will you know?

        Without monitoring, users discover the problem before developers.

     Monitoring tools collect information like:
        CPU Usage
        Memory Usage
        Response Time
        Error Rate
        Availability

    Real-Life Analogy
        Hospital
        Patients are connected to monitors.
        Doctors immediately know if something goes wrong.
        Similarly, Monitoring tools continuously watch Microservices.
*/