/*

    # Generating a Project Token in SonarQube Dashboard :
    A Project Token is a unique secret key generated by SonarQube to authenticate a project or build tool.

    Project Token = Password for your project (not for the user).
    Instead of using your username and password every time, SonarQube allows you to use a secure token.

    Why do we need a Project Token?
     Imagine anyone could send reports to your SonarQube Server.
        Someone could:
            Upload fake reports
            Modify project data
            Access analysis results
        To prevent this, SonarQube verifies that the request comes from an authorized source.
        That's why a Project Token is required.
        
    Steps to Generate a Project Token:
        1. Log in to the SonarQube Dashboard.
        2. Click on your profile icon (top-right corner).
        3. Select "My Account".
        4. Go to "Security" tab.
        5. Under "Project Tokens", click "Generate".
        6. Enter a token name (e.g., "maven-project-token").
        7. Click "Generate".
        8. Copy the token value (you won’t see it again).

    Use the token in your Maven command:
        mvn clean verify sonar:sonar -Dsonar.login=your_project_token_here

    Why Use a Project Token?
        Security: Tokens are more secure than passwords.
        Reuse: You can use the same token for multiple builds.
        Clean Access: Tokens can be revoked anytime without affecting user accounts.

    # Viewing Scan Results on the Dashboard :
        After the analysis completes, SonarQube displays a dashboard containing the project's quality metrics.

     What can you see?
        Typical dashboard:
            Project : Banking Application
            Quality Gate : PASSED
            Bugs : 2
            Security : 1
            Code Smells : 12
            Coverage : 84%
            Duplicated Code : 3%

        1. Quality Gate: Overall project status.
            Passed
            Failed
            
        2. Bugs:    Programming errors that may cause incorrect behavior.
            Example:
                String name = null;
                System.out.println(name.length());
            Possible NullPointerException.

        3. Vulnerabilities : Security-related issues.
            Example:
                String query = "SELECT * FROM users WHERE id=" + input;

            Possible SQL Injection.

        4. Code Smells : Poor coding practices.
            Examples:
                Long methods
                Unused variables
                Duplicate code
                Poor naming
            
        5. Coverage : Shows how much of the code is tested.
            Example:
                Coverage = 85%
            Means approximately 85% of the code is executed by unit tests.

        6. Duplicated Code : Shows how much code has been copied.
            Lower duplication means better maintainability.

    # Interpreting Sonar Logs :
    When Maven runs SonarQube, messages appear in the terminal.
        These are called Sonar Logs.
        Logs tell you:
            What is happening
            Whether analysis succeeded
            If any errors occurred

*/